# Generated by Django 2.2.2 on 2019-06-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DifferenceN',
            fields=[
                ('n', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('value', models.IntegerField(default=0)),
                ('occurences', models.IntegerField(default=0)),
            ],
        ),
    ]
