# Generated by Django 2.2.2 on 2019-06-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('difference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeqABC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.IntegerField()),
                ('b', models.IntegerField()),
                ('c', models.IntegerField()),
                ('pythagorean_triple', models.BooleanField(default=False)),
                ('seq_sum', models.IntegerField(default=0)),
                ('occurences', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('a', 'b', 'c')},
            },
        ),
    ]
